export const statuses = [
  'busy',
  'working',
  'loving',
  'petting',
  'taking care of pets',
  'playing with Pepé',
  'playing with Chips',
  'outdoors',
  'drawing',
  'planning',
  'swimming',
  'biking',
  'interviewing',
  'pooping',
  'showering',
  'in the hot tub',
  'watching a streaming service',
  'getting assaulted at Food Lion',
  "hanging out at Bart\\'s",
  'listening to music',
  'coding',
  'working on this website',
  'walking',
  'sleeping',
  'napping',
  'playing video games',
  'watching a movie',
  'doom scrolling',
  'laughing',
  'making a joke',
  'watering plants',
  'cleaning',
  'doing laundry',
];

export const getRandomStatus = () =>
  statuses[Math.floor(Math.random() * statuses.length)];
